apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp-ns-admin
  namespace: default
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kapp-ns-admin
  namespace: default
subjects:
- kind: ServiceAccount
  name: kapp-ns-admin
  namespace: default
# The role binding is restricting this cluster role
# to the "default" namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
