apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: apps
  namespace: apps-mgmt
spec:
  serviceAccountName: kapp-cluster-admin
  fetch:
  - git:
      url: https://github.com/vmware-tanzu-labs/tdc-carvel-examples
      ref: origin/main
      subPath: kapp-controller/apps
  template:
    - ytt: {}
  deploy:
    - kapp: {}