apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: spring-petclinic
  namespace: test
spec:
  serviceAccountName: kapp-ns-admin
  fetch:
  - git:
      url: https://github.com/vmware-tanzu-labs/tdc-carvel-examples
      ref: origin/main
      subPath: template
  template:
  - ytt: {}
  deploy:
  - kapp:
      # All of our apps resources are normally in the default namespace.
      # Here we can re-target the app to be deployed to test.
      mapNs:
        - default=test
